[platformio]
default_envs = esp32doit-devkit-v1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=3
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit SH110X @ ^2.1.11



[env:esp32doit-devkit-v1]
board = esp32doit-devkit-v1
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
build_flags =
  ${env.build_flags}
  -DBOARD_ESP32_DOIT
  -DSTATUS_BUTTON_PIN=12
  -DOLED_SDA_PIN=13
  -DOLED_SCL_PIN=27

[env:waveshare_esp32_s3_zero]
board = waveshare_esp32_s3_zero
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
board_build.flash_mode = dio
board_build.arduino.memory_type = qio_qspi
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_ESP32_S3_ZERO
  -DSTATUS_BUTTON_PIN=10
  -DOLED_SDA_PIN=6
  -DOLED_SCL_PIN=7


 
