name: ESP-IDF Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: ESP-IDF build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3
        target: esp32
        path: '.'
        command: |
          . ${IDF_PATH}/export.sh
          cd ${IDF_PATH}/components
          git clone --depth 1 https://github.com/espressif/arduino-esp32.git arduino
          cd arduino
          git submodule update --init --recursive
          cd /app/${{ github.repository }}
          idf.py build
